// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigureSync(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConfigureSync'](arg1, arg2, arg3);
}

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetSyncSettings() {
  return window['go']['main']['App']['GetSyncSettings']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetTree() {
  return window['go']['main']['App']['GetTree']();
}

export function GetVaultList() {
  return window['go']['main']['App']['GetVaultList']();
}

export function InitVault() {
  return window['go']['main']['App']['InitVault']();
}

export function MoveEntry(arg1, arg2) {
  return window['go']['main']['App']['MoveEntry'](arg1, arg2);
}

export function QuickSwitch(arg1) {
  return window['go']['main']['App']['QuickSwitch'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RemoveVault(arg1) {
  return window['go']['main']['App']['RemoveVault'](arg1);
}

export function RenameEntry(arg1, arg2) {
  return window['go']['main']['App']['RenameEntry'](arg1, arg2);
}

export function SaveAppSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveAppSettings'](arg1, arg2);
}

export function SaveAttachment(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAttachment'](arg1, arg2, arg3);
}

export function SearchNotes(arg1) {
  return window['go']['main']['App']['SearchNotes'](arg1);
}

export function SelectVaultFolder() {
  return window['go']['main']['App']['SelectVaultFolder']();
}

export function SetGitHubPAT(arg1) {
  return window['go']['main']['App']['SetGitHubPAT'](arg1);
}

export function SwitchVault(arg1) {
  return window['go']['main']['App']['SwitchVault'](arg1);
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
