// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function GetTree() {
  return window['go']['main']['App']['GetTree']();
}

export function InitVault() {
  return window['go']['main']['App']['InitVault']();
}

export function MoveEntry(arg1, arg2) {
  return window['go']['main']['App']['MoveEntry'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RenameEntry(arg1, arg2) {
  return window['go']['main']['App']['RenameEntry'](arg1, arg2);
}

export function SelectVaultFolder() {
  return window['go']['main']['App']['SelectVaultFolder']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
