// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vault} from '../models';
import {search} from '../models';

export function CreateFile(arg1:string,arg2:string):Promise<string>;

export function CreateFolder(arg1:string,arg2:string):Promise<string>;

export function DeleteEntry(arg1:string):Promise<void>;

export function GetTree():Promise<vault.Node>;

export function InitVault():Promise<string>;

export function MoveEntry(arg1:string,arg2:string):Promise<string>;

export function QuickSwitch(arg1:string):Promise<Array<string>>;

export function ReadFile(arg1:string):Promise<string>;

export function RenameEntry(arg1:string,arg2:string):Promise<string>;

export function SaveAttachment(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SearchNotes(arg1:string):Promise<Array<search.Result>>;

export function SelectVaultFolder():Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
